// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYwrHriJlEMtLhx-1smy3HTYd1BE6BkYo',
    appId: '1:1095877865430:web:1c03acda8efcc868d7fe77',
    messagingSenderId: '1095877865430',
    projectId: 'memories-705ce',
    authDomain: 'memories-705ce.firebaseapp.com',
    storageBucket: 'memories-705ce.appspot.com',
    measurementId: 'G-4G5R5425FP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBorQ1B6tttvRn_Wk1PESb8ygs4tWpkyhU',
    appId: '1:1095877865430:android:abaad47ad5f73c98d7fe77',
    messagingSenderId: '1095877865430',
    projectId: 'memories-705ce',
    storageBucket: 'memories-705ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKs9H4WVX8SHf4EDg3xwI5cLz8yfyVxH8',
    appId: '1:1095877865430:ios:9b905f56f01aa9a2d7fe77',
    messagingSenderId: '1095877865430',
    projectId: 'memories-705ce',
    storageBucket: 'memories-705ce.appspot.com',
    iosClientId: '1095877865430-tt27sgkdp2nt7lh30pc0l4som5oj0ckt.apps.googleusercontent.com',
    iosBundleId: 'com.example.memories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKs9H4WVX8SHf4EDg3xwI5cLz8yfyVxH8',
    appId: '1:1095877865430:ios:a448df17adca3848d7fe77',
    messagingSenderId: '1095877865430',
    projectId: 'memories-705ce',
    storageBucket: 'memories-705ce.appspot.com',
    iosClientId: '1095877865430-udeioaek2v32or8meb39q8uv52rr33hb.apps.googleusercontent.com',
    iosBundleId: 'com.example.memories.RunnerTests',
  );
}
